TRUNCATE table "F15.C9_RFE_CONTACTS";
TRUNCATE table "F15.C9_RFE_HISTORY";
TRUNCATE table "F19.C9_REF_TASK_RD";
TRUNCATE table "F19.C9_Notice";
TRUNCATE table "F15.C9_Documentation";
TRUNCATE table "F15.C9_RFE_TRACKING_COMMENTS";	
delete from "F15.C9_RFE_EXCEPTION_REQUESTS";
