DROP TABLE "GLOBLE_VALUE";
CREATE TABLE "GLOBLE_VALUE"(
	"GLOBLE_ID" INTEGER NOT NULL,
	"APPLICATION" VARCHAR(255),
	"SAVED VALUE" VARCHAR(30),
	"VALUE" INTEGER
);

INSERT INTO "GLOBLE_VALUE"("GLOBLE_ID","APPLICATION","SAVED VALUE") VALUES(1,'RFE','RFE_ID');

DROP TRIGGER RFE_G_UPDATE_TRIG;


	
